param_table:
  default_column:
    empty_text: N/A
  required_column:
    true_text: "**Required**"
    false_text: "_Optional_"

# Replace text in every description in the spec file
text_replacements:
  - replace: "https://docs.opensearch.org/latest"
    with: "{{site.url}}{{site.baseurl}}"
  - replace: "\n"
    with: " "